
project_id = "kxeffcclfvecdvqpljbh"

[api]
enabled = true

[api.cors]
enabled = true
origins = ["*"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With", "Accept", "Origin"]
exposed_headers = ["Content-Range", "X-Content-Range"]
max_age = 600
credentials = true

[auth]
# These variables are used in the client side React application
site_url = "https://kxeffcclfvecdvqpljbh.lovable.app"  # Replace with your site URL
additional_redirect_urls = ["https://kxeffcclfvecdvqpljbh.lovable.app", "https://kxeffcclfvecdvqpljbh.lovable.app/auth/callback"]

[auth.external.google]
enabled = true

[functions]

[functions.theme-service]
verify_jwt = false

[realtime]
enabled = true
