
// This file is automatically generated. Do not edit it directly.
import { supabase as appSupabase } from '@/integrations/supabase/client';

// Re-export the app's Supabase client
export const supabase = appSupabase;

// For typing purposes
export type Database = any;
